WARNING:root:Traceback (most recent call last):
  File "/home/jj/git/telegram_bot_lua_game/telebot/telebot.py", line 54, in background
    self.__onMessage(u,msg)
  File "/home/jj/git/telegram_bot_lua_game/telebot/telebot.py", line 232, in __onMessage
    self.onMessage(self,u,msg)
  File "main.py", line 52, in onMsg
    playRound(bot,userid = userid,msg = text,level = usrLvl)
  File "main.py", line 74, in playRound
    bot.sendMessage(userid,"%s%s"%log)
TypeError: not enough arguments for format string

WARNING:root:Traceback (most recent call last):
  File "/home/jj/git/telegram_bot_lua_game/telebot/telebot.py", line 54, in background
    self.__onMessage(u,msg)
  File "/home/jj/git/telegram_bot_lua_game/telebot/telebot.py", line 232, in __onMessage
    self.onMessage(self,u,msg)
  File "main.py", line 88, in onMsg
    setLevel(bot,userid,0)
  File "main.py", line 94, in setLevel
    bot.customDB()['users'][userid]['level'] = lvl
KeyError: 452549370

WARNING:root:Traceback (most recent call last):
  File "/home/jj/git/telegram_bot_lua_game/telebot/telebot.py", line 54, in background
    self.__onMessage(u,msg)
  File "/home/jj/git/telegram_bot_lua_game/telebot/telebot.py", line 232, in __onMessage
    self.onMessage(self,u,msg)
  File "main.py", line 88, in onMsg
    setLevel(bot,userid,0)
  File "main.py", line 37, in setLevel
    bot.customDB()['user'][userid]['level'] = i
KeyError: 'user'

WARNING:root:Traceback (most recent call last):
  File "/home/jj/git/telegram_bot_lua_game/telebot/telebot.py", line 54, in background
    self.__onMessage(u,msg)
  File "/home/jj/git/telegram_bot_lua_game/telebot/telebot.py", line 232, in __onMessage
    self.onMessage(self,u,msg)
  File "main.py", line 89, in onMsg
    setLevel(bot,userid,0)
  File "main.py", line 38, in setLevel
    bot.users[userid]['level'] = i
KeyError: 452549370

WARNING:root:Traceback (most recent call last):
  File "/home/jj/git/telegram_bot_lua_game/telebot/telebot.py", line 51, in background
    self.__onCommand(cmd,param,e,u)
  File "/home/jj/git/telegram_bot_lua_game/telebot/telebot.py", line 200, in __onCommand
    if self.__canUserUseComm(userid, cmd):
  File "/home/jj/git/telegram_bot_lua_game/telebot/telebot.py", line 185, in __canUserUseComm
    return c and ( self.__users.isAdmin(userid) or (not 'mustbe' in c) or ('mod'==c['mustbe'] and self.__users.isMod(userid)) )
TypeError: argument of type 'bool' is not iterable

WARNING:root:Traceback (most recent call last):
  File "main.py", line 96, in announceRound
    f = open('level/%s/info.txt'%lvl,'r')
FileNotFoundError: [Errno 2] No such file or directory: 'level/1/info.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jj/git/telegram_bot_lua_game/telebot/telebot.py", line 54, in background
    self.__onMessage(u,msg)
  File "/home/jj/git/telegram_bot_lua_game/telebot/telebot.py", line 232, in __onMessage
    self.onMessage(self,u,msg)
  File "main.py", line 90, in onMsg
    playRound(bot,userid = userid,msg = text)
  File "main.py", line 129, in playRound
    announceRound(bot,userid)
  File "main.py", line 100, in announceRound
    txt = txt or "No lvl Info"
UnboundLocalError: local variable 'txt' referenced before assignment

WARNING:root:Traceback (most recent call last):
  File "main.py", line 97, in announceRound
    f = open('level/%s/info.txt'%lvl,'r')
FileNotFoundError: [Errno 2] No such file or directory: 'level/1/info.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jj/git/telegram_bot_lua_game/telebot/telebot.py", line 54, in background
    self.__onMessage(u,msg)
  File "/home/jj/git/telegram_bot_lua_game/telebot/telebot.py", line 232, in __onMessage
    self.onMessage(self,u,msg)
  File "main.py", line 90, in onMsg
    playRound(bot,userid = userid,msg = text)
  File "main.py", line 130, in playRound
    announceRound(bot,userid)
  File "main.py", line 102, in announceRound
    if f: f.close()
UnboundLocalError: local variable 'f' referenced before assignment

WARNING:root:Traceback (most recent call last):
  File "main.py", line 109, in playRound
    open('level/%s/wrap.lua'%level,'r')
FileNotFoundError: [Errno 2] No such file or directory: 'level/1/wrap.lua'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jj/git/telegram_bot_lua_game/telebot/telebot.py", line 54, in background
    self.__onMessage(u,msg)
  File "/home/jj/git/telegram_bot_lua_game/telebot/telebot.py", line 232, in __onMessage
    self.onMessage(self,u,msg)
  File "main.py", line 90, in onMsg
    playRound(bot,userid = userid,msg = text)
  File "main.py", line 111, in playRound
    sendMessage(userid,'`No level found.`__try /level 0')
NameError: name 'sendMessage' is not defined

WARNING:root:Traceback (most recent call last):
  File "/home/jj/git/telegram_bot_lua_game/telebot/telebot.py", line 51, in background
    self.__onCommand(cmd,param,e,u)
  File "/home/jj/git/telegram_bot_lua_game/telebot/telebot.py", line 203, in __onCommand
    self.onCommand(upd)
TypeError: onCmd() missing 2 required positional arguments: 'update' and 'msg'

WARNING:root:Traceback (most recent call last):
  File "/home/jj/git/telegram_bot_lua_game/telebot/telebot.py", line 51, in background
    self.__onCommand(cmd,param,e,u)
  File "/home/jj/git/telegram_bot_lua_game/telebot/telebot.py", line 203, in __onCommand
    self.onCommand(upd)
TypeError: onCmd() missing 2 required positional arguments: 'update' and 'msg'

WARNING:root:Traceback (most recent call last):
  File "/home/jj/git/telegram_bot_lua_game/telebot/telebot.py", line 51, in background
    self.__onCommand(cmd,param,e,u)
  File "/home/jj/git/telegram_bot_lua_game/telebot/telebot.py", line 203, in __onCommand
    self.onCommand(upd)
TypeError: onCmd() missing 2 required positional arguments: 'update' and 'msg'

WARNING:root:Traceback (most recent call last):
  File "/home/jj/git/telegram_bot_lua_game/telebot/telebot.py", line 54, in background
    self.__onMessage(u,msg)
  File "/home/jj/git/telegram_bot_lua_game/telebot/telebot.py", line 232, in __onMessage
    self.onMessage(self,u,msg)
  File "main.py", line 105, in onMsg
    playRound(bot,userid = userid,msg = text)
  File "main.py", line 127, in playRound
    msgLevelNotFound(bot,userid)
NameError: name 'msgLevelNotFound' is not defined

